all:
	gcc chord_structure_generator.c ~/music/chord_progressions/radial/csg/drawing_service.c ~/music/chord_progressions/radial/csg/dynamic_array.c -o chord_structure_generator -idirafter ../../csg `pkg-config --cflags --libs gtk+-3.0` 

