all:
	gcc chord_structure_generator.c ~/music/analysis_tables/code/drawing_service.c ~/music/analysis_tables/code/dynamic_array.c -o chord_structure_generator -idirafter ../code `pkg-config --cflags --libs gtk+-3.0` 

