# This data file was generated by the Spreadsheet Calculator Improvised (SC-IM)
# You almost certainly shouldn't edit it.

label A0 = "Root"
label A1 = "Intervals"
label A2 = "Duration"
label A3 = "Octave"
goto A1
