# This data file was generated by the Spreadsheet Calculator Improvised (SC-IM)
# You almost certainly shouldn't edit it.

label A0 = "Root"
let B0 = 0
label A1 = "Intervals"
let B1 = 7
let C1 = 4
let D1 = 7
let E1 = 11
let F1 = 0
let G1 = 4
let H1 = 7
let I1 = 11
label A2 = "Duration"
let B2 = 1/4
let C2 = 1/8
let D2 = 1/2
let E2 = 1/8
let I2 = 3/8
label A3 = "Octave"
let B3 = 4
let F3 = 5
goto A3
